import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Fanni és Balázs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="my-5 py-5 text-center">
          <h1 className="display-5">Fanni és Balázs</h1>
          <h2>Hamarosan...</h2>
        </div>
      </main>
    </>
  )
}
